pull_request_rules:
  - name: Automatic merge Scala Steward PRs
    conditions:
      - author=xerial-bot
      - check-success=code format
      - check-success=unit tests
      - check-success=sbt scripted tests
      - or:
        - title~=^Update airframe-
        - title~=^Update sbt-airframe
        - title~=^Update airspec
        - title~=^Update scalafmt-core
        - label=sbt-plugin-update
        - label=test-library-update
        - label=library-update  
    actions:
      merge:
        method: squash
