name: CI

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
  push:
    branches:
      - master
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'

jobs:
  code_format:
    name: code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: scalafmt test
        run: ./sbt scalafmtCheckAll
  unit_test:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.11
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-unittest-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-unittest-
      - name: Unit tests
        run: ./sbt test
  test_sbt_plugin:
    name: sbt scripted tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: openjdk@1.11
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/*.sbt') }}
          restore-keys: ${{ runner.os }}-sbt-
      - name: build plugins
        run: ./sbt publishLocal
      - name: sbt scripted test
        # Skip sbt-sql-td test
        run: ./sbt "scripted sbt-sql/* sbt-sql-sqlite/*"
