name: CI

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - 'project/build.properties'
  push:
    branches:
      - master
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - 'project/build.properties'

jobs:
  code_format:
    name: code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: scalafmt test
        run: ./sbt scalafmtCheckAll
  unit_test:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11
      - name: Unit tests
        run: ./sbt test
  test_sbt_plugin:
    name: sbt scripted tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: olafurpg/setup-scala@v14
        with:
          java-version: openjdk@1.11
      - name: build plugins
        run: ./sbt publishLocal
      - name: sbt scripted test
        # Skip sbt-sql-td test
        run: ./sbt "scripted sbt-sql/* sbt-sql-sqlite/*"
