name: CI

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - 'project/build.properties'
  push:
    branches:
      - master
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - 'project/build.properties'

jobs:
  code_format:
    name: code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: scalafmt test
        run: ./sbt scalafmtCheckAll
  unit_test:
    name: unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Unit tests
        run: ./sbt test
  test_sbt_plugin:
    name: sbt scripted tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala-version: ['2.12', '3']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: sbt scripted test
        # Skip sbt-sql-td test
        run: ./sbt "++ ${{ matrix.scala-version }}" "scripted sbt-sql/* sbt-sql-sqlite/*"
